-- 1. Top 5 employees with highest sales

SELECT EmployeeID,
SUM(SaleAmount) AS TotalRevenue
FROM Sales
GROUP BY EmployeeID
ORDER BY TotalRevenue DESC
LIMIT 5;


-- 2. Customers having multiple opportunities

SELECT CustomerID,
COUNT(*) AS OpportunityCount
FROM Opportunities
GROUP BY CustomerID
HAVING COUNT(*) > 1;


-- 3. City generating maximum revenue

SELECT ci.CityName,
SUM(s.SaleAmount) AS Revenue
FROM Sales s
JOIN Customers c
ON s.CustomerID = c.CustomerID
JOIN Cities ci
ON c.CityID = ci.CityID
GROUP BY ci.CityName
ORDER BY Revenue DESC
LIMIT 1;


-- 4. Customers who raised more than 3 tickets

SELECT CustomerID,
COUNT(*) AS TicketCount
FROM SupportTickets
GROUP BY CustomerID
HAVING COUNT(*) > 3;


-- 5. Most common lead source

SELECT ls.SourceName,
COUNT(*) AS LeadCount
FROM Leads l
JOIN LeadSources ls
ON l.SourceID = ls.SourceID
GROUP BY ls.SourceName
ORDER BY LeadCount DESC
LIMIT 1;


-- 6. Employees whose average feedback rating exceeds 4.5

SELECT e.EmployeeID,
e.EmployeeName,
AVG(f.Rating) AS AvgRating
FROM Employees e
JOIN CustomerInteractions ci
ON e.EmployeeID = ci.EmployeeID
JOIN Feedback f
ON ci.CustomerID = f.CustomerID
GROUP BY e.EmployeeID,e.EmployeeName
HAVING AVG(f.Rating) > 4.5;


-- 7. Second highest revenue customer

SELECT CustomerID,
SUM(SaleAmount) AS Revenue
FROM Sales
GROUP BY CustomerID
ORDER BY Revenue DESC
LIMIT 1 OFFSET 1;


-- 8. Employees with maximum closed deals

SELECT EmployeeID,
COUNT(*) AS ClosedDeals
FROM Sales
GROUP BY EmployeeID
ORDER BY ClosedDeals DESC;


-- 9. Average sale amount by city

SELECT ci.CityName,
AVG(s.SaleAmount) AS AverageSale
FROM Sales s
JOIN Customers c
ON s.CustomerID = c.CustomerID
JOIN Cities ci
ON c.CityID = ci.CityID
GROUP BY ci.CityName;


-- 10. Top 10 customers by revenue

SELECT CustomerID,
SUM(SaleAmount) AS Revenue
FROM Sales
GROUP BY CustomerID
ORDER BY Revenue DESC
LIMIT 10;


-- 11. Customers who never converted from lead to sale

SELECT CustomerID
FROM Leads
WHERE CustomerID NOT IN
(
SELECT CustomerID
FROM Sales
);


-- 12. Duplicate customer records based on email

SELECT Email,
COUNT(*) AS DuplicateCount
FROM Customers
GROUP BY Email
HAVING COUNT(*) > 1;


-- 13. Percentage contribution of each employee to total revenue

SELECT EmployeeID,
ROUND(
SUM(SaleAmount)*100/
(SELECT SUM(SaleAmount) FROM Sales),2
) AS RevenuePercentage
FROM Sales
GROUP BY EmployeeID;


-- 14. Percentage contribution of each city to total revenue

SELECT ci.CityName,
ROUND(
SUM(s.SaleAmount)*100/
(SELECT SUM(SaleAmount) FROM Sales),2
) AS RevenuePercentage
FROM Sales s
JOIN Customers c
ON s.CustomerID = c.CustomerID
JOIN Cities ci
ON c.CityID = ci.CityID
GROUP BY ci.CityName;


-- 15. Employee performance ranking

SELECT
e.EmployeeID,
e.EmployeeName,
SUM(s.SaleAmount) AS RevenueGenerated,
RANK() OVER(
ORDER BY SUM(s.SaleAmount) DESC
) AS PerformanceRank
FROM Employees e
JOIN Sales s
ON e.EmployeeID=s.EmployeeID
GROUP BY e.EmployeeID,e.EmployeeName;


-- 16. Find total revenue generated by each department

SELECT d.DepartmentName,
SUM(s.SaleAmount) AS Revenue
FROM Departments d
JOIN Employees e
ON d.DepartmentID=e.DepartmentID
JOIN Sales s
ON e.EmployeeID=s.EmployeeID
GROUP BY d.DepartmentName;


-- 17. Find customers who purchased the most expensive product

SELECT DISTINCT c.CustomerName
FROM Customers c
JOIN Orders o
ON c.CustomerID=o.CustomerID
JOIN OrderDetails od
ON o.OrderID=od.OrderID
WHERE od.ProductID=
(
SELECT ProductID
FROM Products
ORDER BY Price DESC
LIMIT 1
);


-- 18. Find campaign with highest customer response

SELECT CampaignID,
COUNT(*) AS TotalResponses
FROM CampaignResponses
GROUP BY CampaignID
ORDER BY TotalResponses DESC
LIMIT 1;


-- 19. Find monthly revenue trend

SELECT MONTH(SaleDate) AS MonthNo,
SUM(SaleAmount) AS Revenue
FROM Sales
GROUP BY MONTH(SaleDate)
ORDER BY MonthNo;


-- 20. Find customers who purchased more than one product

SELECT o.CustomerID,
COUNT(DISTINCT od.ProductID) AS ProductCount
FROM Orders o
JOIN OrderDetails od
ON o.OrderID=od.OrderID
GROUP BY o.CustomerID
HAVING COUNT(DISTINCT od.ProductID) > 1;